"""
PDF Report Generator for KneeAI Analyzer Research Knee Analysis Reports.
Uses ReportLab to generate multi-section PDF documents with diagnostic images,
tabular metrics, and safety disclaimers.
"""

from pathlib import Path
from typing import Any, Dict, Optional
import os
import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image as RLImage,
    KeepTogether,
    HRFlowable,
)


def generate_pdf_report(
    report_dict: Dict[str, Any],
    output_pdf_path: Path,
    image_card_path: Optional[Path] = None,
) -> Path:
    """
    Generate a research knee analysis report PDF.
    """
    output_pdf_path.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(
        str(output_pdf_path),
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Heading1"],
        fontSize=18,
        leading=22,
        textColor=colors.HexColor("#0f172a"),
        fontName="Helvetica-Bold",
        spaceAfter=2,
    )
    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#0284c7"),
        fontName="Helvetica-Bold",
        spaceAfter=8,
    )
    h2_style = ParagraphStyle(
        "SectionHeader",
        parent=styles["Heading2"],
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#1e293b"),
        fontName="Helvetica-Bold",
        spaceBefore=10,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "BodyTextCustom",
        parent=styles["Normal"],
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor("#334155"),
        fontName="Helvetica",
    )
    disclaimer_style = ParagraphStyle(
        "DisclaimerText",
        parent=styles["Normal"],
        fontSize=7.5,
        leading=10.5,
        textColor=colors.HexColor("#b45309"),
        fontName="Helvetica-Bold",
        alignment=1,
    )

    story = []

    # 1. Header Banner & Title
    story.append(Paragraph("KneeAI Analyzer", title_style))
    story.append(Paragraph("RESEARCH KNEE ANALYSIS & JSW PROFILING REPORT", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#0284c7"), spaceAfter=8))

    # 2. Disclaimer Box
    disclaimer_text = (
        "<b>RESEARCH / PROTOTYPE OUTPUT ONLY:</b> This report is generated by an artificial intelligence research prototype "
        "for computational assessment. It does NOT provide a clinical diagnosis, osteoarthritis grading, treatment plan, "
        "or surgical decision. Physical measurements require verified DICOM pixel spacing."
    )
    disclaimer_table = Table([[Paragraph(disclaimer_text, disclaimer_style)]], colWidths=[540])
    disclaimer_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#fef3c7")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#f59e0b")),
            ("PADDING", (0, 0), (-1, -1), 6),
        ])
    )
    story.append(disclaimer_table)
    story.append(Spacer(1, 10))

    # 3. Patient & Scan Overview Table
    pat = report_dict.get("patient_scan_info", {})
    img_info = report_dict.get("image_information", {})
    proc = report_dict.get("processing", {})

    info_data = [
        [
            Paragraph("<b>Scan ID:</b>", body_style),
            Paragraph(str(pat.get("scan_id", "N/A")), body_style),
            Paragraph("<b>Patient Code:</b>", body_style),
            Paragraph(str(pat.get("patient_code", "N/A")), body_style),
        ],
        [
            Paragraph("<b>File Name:</b>", body_style),
            Paragraph(str(pat.get("filename", "N/A")), body_style),
            Paragraph("<b>Native Dimensions:</b>", body_style),
            Paragraph(f"{img_info.get('native_width', '--')} x {img_info.get('native_height', '--')} px", body_style),
        ],
        [
            Paragraph("<b>Generated At:</b>", body_style),
            Paragraph(str(report_dict.get("generated_at", datetime.datetime.utcnow().isoformat())), body_style),
            Paragraph("<b>Processing Latency:</b>", body_style),
            Paragraph(f"{proc.get('processing_time_ms', '--')} ms ({proc.get('device', 'CPU')})", body_style),
        ],
    ]
    info_table = Table(info_data, colWidths=[110, 160, 120, 150])
    info_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("PADDING", (0, 0), (-1, -1), 4),
        ])
    )
    story.append(Paragraph("1. Analysis & Scan Information", h2_style))
    story.append(info_table)
    story.append(Spacer(1, 8))

    # 4. Quantitative Measurements & QC Table
    seg = report_dict.get("segmentation", {})
    jsw = report_dict.get("jsw_measurements", {})
    cal = report_dict.get("calibration", {})
    qc = report_dict.get("quality_control", {})
    res_assess = report_dict.get("research_assessment", {})

    meas_data = [
        [
            Paragraph("<b>Parameter</b>", body_style),
            Paragraph("<b>Quantitative Value</b>", body_style),
            Paragraph("<b>Quality / Assessment</b>", body_style),
        ],
        [
            Paragraph("Segmentation Model", body_style),
            Paragraph("MONAI 2D U-Net (v2)", body_style),
            Paragraph(f"Quality: <b>{seg.get('quality', '--')}</b>", body_style),
        ],
        [
            Paragraph("Foreground Joint Area", body_style),
            Paragraph(f"{seg.get('foreground_pixels', 0):,} px ({seg.get('area_percentage', 0.0):.2f}%)", body_style),
            Paragraph(f"Top-2 Lobes: {seg.get('top2_components_ratio', 0.0)*100:.1f}% mass", body_style),
        ],
        [
            Paragraph("Median JSW Clearance", body_style),
            Paragraph(f"<b>{jsw.get('median_px', '--')} px</b>", body_style),
            Paragraph(f"Range: {jsw.get('min_px', '--')} px - {jsw.get('max_px', '--')} px", body_style),
        ],
        [
            Paragraph("Profile Sample Count", body_style),
            Paragraph(f"{jsw.get('sample_count', 0)} column cross-sections", body_style),
            Paragraph(f"Asymmetry Ratio: {jsw.get('compartment_asymmetry_ratio') or '--'}", body_style),
        ],
        [
            Paragraph("Physical Calibration", body_style),
            Paragraph(f"Unit: <b>{cal.get('unit', 'pixels')}</b>", body_style),
            Paragraph("Uncalibrated PNG (Pixel measurements only)", body_style) if not cal.get("available") else Paragraph("Calibrated from DICOM spacing", body_style),
        ],
        [
            Paragraph("Quality Control Status", body_style),
            Paragraph(f"<b>{qc.get('status', '--')}</b>", body_style),
            Paragraph(f"Reliability Score: <b>{res_assess.get('measurement_reliability_score', '--')} / 1.00</b>", body_style),
        ],
    ]
    meas_table = Table(meas_data, colWidths=[150, 190, 200])
    meas_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0284c7")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("PADDING", (0, 0), (-1, -1), 4),
        ])
    )
    story.append(Paragraph("2. Native-Space Geometry & JSW Measurements", h2_style))
    story.append(meas_table)
    story.append(Spacer(1, 8))

    # 5. Non-Diagnostic Research Observations & Warnings
    obs_list = res_assess.get("observations", [])
    obs_paragraphs = [Paragraph(f"• {obs}", body_style) for obs in obs_list] if obs_list else [Paragraph("• No specific observations recorded.", body_style)]

    warn_list = qc.get("warning_reasons", []) + qc.get("invalid_reasons", [])
    warn_paragraphs = [Paragraph(f"• <font color='#b45309'><b>Warning:</b> {w}</font>", body_style) for w in warn_list] if warn_list else [Paragraph("• None (All geometry and sampling parameters within nominal bounds).", body_style)]

    obs_table_data = [
        [Paragraph("<b>Research Observations (Non-Diagnostic)</b>", body_style), Paragraph("<b>Quality Warnings & Notes</b>", body_style)],
        [obs_paragraphs, warn_paragraphs],
    ]
    obs_table = Table(obs_table_data, colWidths=[270, 270])
    obs_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("PADDING", (0, 0), (-1, -1), 5),
        ])
    )
    story.append(Paragraph("3. Assessment Observations & Integrity Audit", h2_style))
    story.append(obs_table)
    story.append(Spacer(1, 10))

    # 6. Attached Visual Report Image Card
    if image_card_path and Path(image_card_path).exists():
        story.append(Paragraph("4. Diagnostic Visual Validation Card", h2_style))
        rl_img = RLImage(str(image_card_path), width=540, height=170)
        story.append(rl_img)
        story.append(Spacer(1, 6))

    # 7. Final Footer Safety Notice
    footer_text = (
        "<b>LEGAL & CLINICAL SAFETY NOTICE:</b> KneeAI Analyzer is an investigative AI research application. "
        "It is not cleared by medical regulatory authorities. Any quantitative outputs are computational "
        "features and must be verified by a qualified radiologist or orthopedic specialist."
    )
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cbd5e1"), spaceBefore=6, spaceAfter=4))
    story.append(Paragraph(footer_text, ParagraphStyle("FooterNotice", parent=styles["Normal"], fontSize=7, leading=9, textColor=colors.HexColor("#64748b"), alignment=1)))

    doc.build(story)
    return output_pdf_path
